services:
  worker:
    build:
      context: .
      args:
        TORCH_EXTRA_INDEX: https://download.pytorch.org/whl/cu126
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]